name: PetBuddy
options:
  bundleIdPrefix: com.pxlborn
  deploymentTarget:
    iOS: 16.2
packages:
  Drops:
    url: https://github.com/omaralbeik/Drops.git
    from: 1.6.1
targets:
  PetBuddy:
    info:
      path: PetBuddy/Resources/Info.generated.plist
      properties:
        CFBundleDisplayName: "PetBuddy"
        UILaunchScreen: []
        UIUserInterfaceStyle: "Light"
    type: application
    platform: iOS
    sources:
      - path: PetBuddy
    dependencies:
      - package: Drops
    scheme:
      testTargets:
      - PetBuddy-Tests
    preBuildScripts:
      - name: SwiftLint
        script: |
                export PATH="$PATH:/opt/homebrew/bin"
                if which swiftlint > /dev/null; then
                  swiftlint
                else
                  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
        outputFiles:
          - $(DERIVED_FILE_DIR)/swiftlint-output
  PetBuddy-Tests:
    info:
      path: PetBuddyTests/Resources/Info.generated.plist
      properties:
        CFBundleDisplayName: "PetBuddy-Tests"
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PetBuddyTests
