name: PetBuddy
options:
  bundleIdPrefix: com.pxlborn
  deploymentTarget:
    iOS: 16.2
packages:
  Drops:
    url: https://github.com/omaralbeik/Drops.git
    from: 1.6.1
  Realm:
    url: https://github.com/realm/realm-core.git
    from: 13.17.1
  RealmSwift:
    url: https://github.com/realm/realm-swift.git
    from: 10.42.0
targets:
  PetBuddy:
    info:
      path: PetBuddy/Resources/Info.generated.plist
      properties:
        CFBundleDisplayName: "PetBuddy"
        UILaunchScreen: []
        UIUserInterfaceStyle: "Light"
        NSCameraUsageDescription: "Your app would like to access the camera to capture photos and videos."
        NSPhotoLibraryUsageDescription: "Your app would like to access your photo library to select and import photos."
        NSPhotoLibraryAddUsageDescription: "Your app would like to save photos to your photo library."
    type: application
    platform: iOS
    sources:
      - path: PetBuddy
    dependencies:
      - package: Drops
      - package: Realm
      - package: RealmSwift
    scheme:
      testTargets:
      - PetBuddy-Tests
    preBuildScripts:
      - name: SwiftLint
        script: |
                export PATH="$PATH:/opt/homebrew/bin"
                if which swiftlint > /dev/null; then
                  swiftlint
                else
                  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
        outputFiles:
          - $(DERIVED_FILE_DIR)/swiftlint-output
  PetBuddy-Tests:
    info:
      path: PetBuddyTests/Resources/Info.generated.plist
      properties:
        CFBundleDisplayName: "PetBuddy-Tests"
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PetBuddyTests
